module.exports = {
    sumatera: {
      aceh: ['banda_aceh', 'langsa', 'meulaboh', 'lhokseumawe', 'sabang', 'subulussalam'],
      sumatera_utara: ['medan', 'binjai', 'gunung sitoli', 'padangsidimpuan', 'pematangsiantar', 'sibolga', 'tanjungbalai', 'tebing tinggi'],
      sumatera_barat: ['bukit tinggi', 'padang', 'padang panjang', 'periaman', 'payakumbuh', 'sawahlunto', 'solok'],
      riau: ['dumai', 'pekanbaru'],
      jambi: ['sungai penuh', 'jambi'],
      bengkulu: ['bengkulu'],
      lampung: ['bandar lampung', 'metro'],
      kepulauan_riau: ['batam', 'tanjung pinang'],
      kepulauan_bangka_belitung: ['pangkalpinang'],
      sumatera_selatan: ['lubuklinggau', 'pagaralam', 'palembang', 'prabumulih'],
    },
    jawa: {
      DKI_jakarta: ['jakarta barat', 'jakarta pusat', 'jakarta selatan', 'jakarta timur', 'jakarta utara'],
      jawa_barat: ['bandung', 'bekasi', 'bogor', 'cimahi', 'cirebon', 'depok', 'sukabumi', 'tasikmalaya', 'banjar'],
      jawa_tengah: ['magelang', 'pekalongan', 'purwokerto', 'salatiga', 'semarang', 'surakarta', 'tegal'],
      DI_yogyakarta: ['yogyakarta', 'sleman', 'bantul'],
      jawa_timur: ['batu', 'blitar', 'kediri', 'madiun', 'malang', 'mojokerto', 'pasuruan', 'probolinggo', 'surabaya'],
      banten: ['cilegon', 'serang', 'tanggerang'],
    },
    nusa_tenggara: {
      bali: ['denpasar'],
      nusa_tenggara_barat: ['bima', 'mataram'],
      nusa_tenggara_timur: ['kupang'],
    },
    kalimantan: {
      kalimantan_timur: ['balikpapan', 'bontang'],
      kalimantan_selatan: ['banjarbaru', 'banjarmasin'],
      kalimantan_utara: ['tarakan'],
      kalimantan_barat: ['pontianak', 'singkawang'],
      kalimantan_tengah: ['palangkaraya'],
    },
    sulawesi: {
      sulawesi_utara: ['bitung', 'kotamobagu', 'manado', 'tomohon'],
      sulawesi_tengah: ['palu'],
      sulawesi_selatan: ['makassar', 'parepare', 'palopo'],
      sulawesi_tenggara: ['bau bau', 'kendari'],
      gorontalo: ['gorontalo'],
    },
    maluku: {
        maluku: ['ambon', 'tual'],
        maluku_utara: ['temate', 'tidore'],
    },
    papua: {
      papua: ['jayapura'],
      papua_barat: ['manokwari'],
      papua_selatan: ['merauke'],
      papua_tengah: ['nabire'],
      papua_pegunungan: ['jayawijaya'],
      papua_barat_daya: ['sorong'],
    },
  };